Rabbitmq health check
naoned/rabbitmq-docker pull request #3
Opened 2017-06-22 13:48 UTC by vcollignon

2017-06-23 07:39 UTC, seblavenant requested changes

2017-06-23 07:39 UTC, seblavenant commented on scripts/service-checker.sh
> +#!/bin/sh
a déplacer dans onyx-org/core ?

2017-06-23 07:39 UTC, seblavenant commented on scripts/healthcheck/rabbitmq.sh
> +exit 1
saut de ligne fin de fichier

2017-06-23 07:39 UTC, seblavenant commented on rabbitmq.mk
> +		echo 'Creating rabbitmq container'; \
dans les script bash il faut indenter avec des espaces

2017-06-29 08:48 UTC, lebris requested changes

2017-06-29 08:48 UTC, lebris commented on Dockerfile
> +RUN apt-get update && apt-get install -y curl
Manque le nettoyage après
```Dockerfile
RUN apt-get update && \
         apt-get install -y curl && \
         apt-get -y autoremove && \
         rm -rf /var/lib/apt/lists/*
```

2017-06-29 08:48 UTC, lebris commented on docker-compose.yml
> +        healthcheck:
on est sur une image à nous, on peut gérer le healthcheck par défaut directement dans le `Dockerfile`

2017-06-29 12:55 UTC, seblavenant commented on docker-compose.yml
> +        healthcheck:
fixed 564850af15f08ae26f19a34ee1154cfb0e74b722

2017-06-29 12:55 UTC, seblavenant commented on Dockerfile
> +RUN apt-get update && apt-get install -y curl
fixed 80cbaca6ced8d793d235f3cb3831efc045132d77

2017-06-29 14:15 UTC, lebris requested changes

2017-06-29 14:15 UTC, lebris commented on docker-compose.yml
> +        healthcheck:
A gérer aussi dans l'image https://docs.docker.com/engine/reference/builder/#healthcheck

2017-07-04 08:03 UTC, seblavenant commented on docker-compose.yml
> +        healthcheck:
fixed 		f67b9af

2017-07-05 07:07 UTC, seblavenant approved these changes

2017-07-05 09:00 UTC, lebris approved these changes

2017-07-05 09:17 UTC, merged

2017-07-11 08:24 UTC, lebris commented on rabbitmq.mk
> +	@if [ -z "$$(docker ps -a --filter name=rabbitmq --format {{.Names}} | grep -E '^rabbitmq$$')" ]; then \
Nop, corrigé dans https://github.com/naoned/rabbitmq-docker/commit/5ed6d3995c7a860f622d761b57d2c2537b38c9ff